# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-12 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyTin_View', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='short_descr',
            field=models.CharField(default='This is adbobe photoshop to edit and generate amazing graphical contents and clearout images', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='software',
            name='descr',
            field=models.CharField(max_length=600),
        ),
    ]
