# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-12 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyTin_View', '0002_auto_20180312_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='isOs',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
