# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-12 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyTin_View', '0003_software_isos'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('short_descr', models.CharField(max_length=300)),
                ('descr', models.CharField(max_length=600)),
            ],
        ),
        migrations.RenameField(
            model_name='software',
            old_name='more_link',
            new_name='version',
        ),
    ]
