# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-10 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CyTin_View', '0006_requestnew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='requestnew',
            options={'verbose_name_plural': 'RequestNew'},
        ),
    ]
